swagger: "2.0"

info:
  title: "NVIDIA Clara Segmentation"
  version: "1.0"

basePath: /v1

paths:
  /nvidiaclarasegmentation/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
        - name: segmentationformdata
          in: body
          schema:
            $ref: '#definitions/segmentationformdata'
      responses:
        200:
          description: OK

  /inference/:
    get:
      operationId: api.inference.get
      parameters:
      parameters:
        - name: auth_token
          in: query
          type: string
        - name: taskid
          in: query
          type: string
        - name: jobid
          in: query
          type: string
        - name: mlmodelid
          in: query
          type: string
      responses:
        200:
          description: OK


  /finetunelocal/:
    get:
      operationId: api.finetunelocal.get
      parameters:
      parameters:
        - name: auth_token
          in: query
          type: string
        - name: taskid
          in: query
          type: string
        - name: jobid
          in: query
          type: string
        - name: mlmodelid
          in: query
          type: string
        - name: annotatoremail
          in: query
          type: string
        - name: modelversion
          in: query
          type: string
      responses:
        200:
          description: OK

  /launchslicer/:
    get:
      operationId: api.launchslicer.get
      parameters:
        - name: auth_token
          in: query
          type: string
        - name: taskid
          in: query
          type: string
        - name: jobid
          in: query
          type: string
        - name: useremail
          in: query
          type: string
      responses:
        200:
          description: OK

definitions:
  inferencedata:
    type: object
    properties:
     taskid:
      type: array
      items:
        type: string
     jobid:
      type: array
      items:
        type: string
     modelid:
      type: array
      items:
        type: string
  segmentationformdata:
    type: object
    properties:
     seriesjson:
      type: array
      items:
        type: string
     directorypath:
      type: array
      items:
        type: string
     aiserver:
      type: array
      items:
        type: string
     aimodel:
      type: array
      items:
        type: string

